version: '3.4'

services:
  presentation.intranet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
        - "5000:80"
  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
        - "3000:3000"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"