version: '3.4'

services:

  presentation.intranet.api:
    image: ${DOCKER_REGISTRY-}presentationintranetapi
    build:
      context: .
      dockerfile: Web/Presentation.Intranet.Api/Dockerfile

  
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: Web/extranet/web-calendar
      dockerfile: Dockerfile

